export const swords = [
  {
      id: 1,
      name: "Начальный меч",
      damage: 6,
      criticalDamage: 9,
      level: 1,
      maxLevel: 3,
      upgradeCost: 100,
      eachUpgradeCost: 100,
      upgradeDamage: 3,
      upgradeCriticalDamage: 5,
      price: 0
  },
  {
      id: 2,
      name: "Ржавый тесак",
      damage: 12,
      criticalDamage: 16,
      level: 1,
      maxLevel: 3,
      upgradeCost: 150,
      eachUpgradeCost: 120,
      upgradeDamage: 5,
      upgradeCriticalDamage: 8,
      price: 150
  },
  {
      id: 3,
      name: "Стальной гладиус",
      damage: 22,
      criticalDamage: 30,
      level: 1,
      maxLevel: 4,
      upgradeCost: 250,
      eachUpgradeCost: 150,
      upgradeDamage: 8,
      upgradeCriticalDamage: 12,
      price: 450
  },
  {
      id: 4,
      name: "Алмазный меч",
      damage: 38,
      criticalDamage: 55,
      level: 1,
      maxLevel: 4,
      upgradeCost: 400,
      eachUpgradeCost: 250,
      upgradeDamage: 12,
      upgradeCriticalDamage: 20,
      price: 900
  },
  {
      id: 5,
      name: "Теневой кинжал",
      damage: 55,
      criticalDamage: 90,
      level: 1,
      maxLevel: 5,
      upgradeCost: 600,
      eachUpgradeCost: 350,
      upgradeDamage: 18,
      upgradeCriticalDamage: 35,
      price: 1800
  },
  {
      id: 6,
      name: "Подземельный меч",
      damage: 85,
      criticalDamage: 130,
      level: 1,
      maxLevel: 5,
      upgradeCost: 900,
      eachUpgradeCost: 500,
      upgradeDamage: 25,
      upgradeCriticalDamage: 45,
      price: 3500
  },
  {
      id: 7,
      name: "Клинок вечного пламени",
      damage: 130,
      criticalDamage: 200,
      level: 1,
      maxLevel: 5,
      upgradeCost: 1500,
      eachUpgradeCost: 800,
      upgradeDamage: 40,
      upgradeCriticalDamage: 65,
      price: 6500
  },
  {
      id: 8,
      name: "Убийца драконов",
      damage: 210,
      criticalDamage: 320,
      level: 1,
      maxLevel: 6,
      upgradeCost: 2500,
      eachUpgradeCost: 1200,
      upgradeDamage: 60,
      upgradeCriticalDamage: 95,
      price: 12000
  },
  {
      id: 9,
      name: "Световой каратель",
      damage: 340,
      criticalDamage: 500,
      level: 1,
      maxLevel: 6,
      upgradeCost: 4000,
      eachUpgradeCost: 2000,
      upgradeDamage: 95,
      upgradeCriticalDamage: 150,
      price: 22000
  },
  {
      id: 10,
      name: "Меч Истинного Повелителя",
      damage: 550,
      criticalDamage: 850,
      level: 1,
      maxLevel: 10,
      upgradeCost: 8000,
      eachUpgradeCost: 4000,
      upgradeDamage: 150,
      upgradeCriticalDamage: 250,
      price: 50000
  }
]